#!/usr/bin/with-contenv bash

cd /app/hydra2 || exit

exec \
	s6-setuidgid abc \
	java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify \
	-Dspring.output.ansi.enabled=ALWAYS -jar /app/hydra2/lib/core-exec.jar help \
	--nobrowser --port  5075 --datafolder /config
