#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*           This image has been deprecated           *
*                                                    *
*           Please switch to the new version         *
*                        at                          *
*                                                    *
*               linuxserver/nzbhydra2                *
*                                                    *
*   https://hub.docker.com/r/linuxserver/nzbhydra2   *
*                                                    *
*  https://github.com/linuxserver/docker-nzbhydra2   *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
